name: "Cross Rust Action"
description: "A github action for cross rust build."
author: "neodyland"

inputs:
  rusttarget:
    description: "Rust target triple"
    required: true
  zigtarget:
    description: "Zig target triple"
    required: true
  sh:
    description: "Shell to execute commands"
    required: false
    default: "/bin/sh"
  storedir:
    description: "Store directory"
    required: false
    default: "./target/cross-rust"
  cargo-build-args:
    description: "Arguments passed to cross-cargo-build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: mlugg/setup-zig@v2
    - uses: oven-sh/setup-bun@v2
    - name: Run
      shell: bash
      run: |
        PATH_TO_CROSS=$(bun setup.js --rusttarget ${{ inputs.rusttarget }} --zigtarget ${{ inputs.zigtarget }} --dir ${{ inputs.storedir }} --sh ${{ inputs.sh }})
        if [ $? -eq 0 ]; then
          $PATH_TO_CROSS ${{ inputs.cargo-build-args }}
        else
          echo "$PATH_TO_CROSS"
          exit 1
        fi
