name: "Cross Rust Action"
description: "A github action for cross rust build."
author: "neodyland"
branding:
  icon: "git-branch"
  color: "green"
inputs:
  cargo-build-args:
    description: "Arguments passed to cross-cargo-build"
    required: false
    default: ""
  toolchain:
    description: "Rust toolchain to use"
    required: false
    type: string
    default: "stable"
  target:
    description: "Rust target triple"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        target: ${{ inputs.target }}
        components: rust-src
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Run
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        uvx cargo-zigbuild +${{ inputs.toolchain }} zigbuild --target ${{ inputs.target }} ${{ inputs.cargo-build-args }}